### ISSUE TITLE
Error: Not enough memory on 2.2.1N439 opentx nightly

### ISSUE THREAD

**Issue by brycedjohnson** [betaflight/betaflight-tx-lua-scripts#97]
Was testing out the latest opentx nightly for a different reason and I saw I was getting a memory error.  Seems to happen after paging through a few lua screens.

Script Syntax Error
BF/ui.lua:335
not enough memory

**Comment by codecae** [comment]
@brycedjohnson did you download the source or use the release zip file?

**Comment by brycedjohnson** [comment]
@codecae Release zip file.  Should I try the source?

**Comment by codecae** [comment]
no the release is the smallest in terms of memory.  Which page is loading when you hit the limit?

**Comment by brycedjohnson** [comment]
On the 4th or 5th page in.  Weirdly one time it just worked and I didn't have any issues until I rebooted the taranis.

**Comment by codecae** [comment]
Would you mind trying this zip? 

http://null.eastus.cloudapp.azure.com/job/Betaflight%20Lua%20-%20X7,%20X9,%20X9D,%20X9D+,%20X10,%20X12/24/artifact/obj/*zip*/obj.zip

**Comment by brycedjohnson** [comment]
That seemed to fix it!  Tried it like 3 times and it worked everytime.  Thanks!

**Comment by brycedjohnson** [comment]
Want me to close this issue or want to close it when you reference whatever fix you did?  Thanks for the quick help!

**Comment by codecae** [comment]
I'd like to leave it open for tracking purposes.

Glad it helped you :)

@mikeller Looks like the Jenkins build didn't have the -s switch for luac.  Should we do an increment release with the current master and include a better build, or should I just update the release zip to contain a build using -s?

**Comment by mikeller** [comment]
@codecae: No problem, we are still in the process of getting this set up. I would say there have been a couple of pretty significant bug fixes since 1.0, so a release 1.0.1 would be in order. (Also, we should totally move to SemVer (https://semver.org/).)

One of the things in SemVer that is sometimes overlooked, but in my opinion is a crucial part of it is 

```
Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.
```

Breaking this rule will create a lot of confusion and frustration amongst users ('I tried v1.0, it did not work, why would I try it again') for no benefit at all (there is an unlimited supply of version numbers, and they are free ;-) ).

**Comment by David-VG** [comment]
I am not sure if it's the same bug or not, but I am using OpenTX 2.2.0 on a Taranis X9D:

Script syntax error
TELEMETRY/bf.lua:10
not enough memory

I get this with the release 1.1 and the file http://null.eastus.cloudapp.azure.com/job/Betaflight%20Lua%20-%20X7,%20X9,%20X9D,%20X9D+,%20X10,%20X12/24/artifact/obj/*zip*/obj.zip

**Comment by David-VG** [comment]
Also disconected but switching between pages I get:

Script syntax error
BF/ui.lua 335
not enought memory

**Comment by David-VG** [comment]
As a little tip: I am using 2 telemetry scripts, one is the betaflight tx lua scripts and the other one: https://github.com/tozes/taranis_telemetry

I am not sure, but maybe betaflight tx lua scripts needs ALL of the available memory.

**Comment by raphaelcoeffic** [comment]
@David-VG yes, definitely! but you could use the one-time script (in `/BF/bf.lua`) for configuring, and the other as a telemetry script for flying.

**Comment by raphaelcoeffic** [comment]
Or just my yourself a brand new shinny X10: no issue with memory there ;-)

**Comment by David-VG** [comment]
I dont get Memory errors that way, (running BF.lua manually). But just wanting to warn about the memory issues. Thanks @raphaelcoeffic

**Comment by mikeller** [comment]
@raphaelcoeffic: Except that the X10 can not (yet) run telemetry scripts at all (as far as I know), and the https://github.com/tozes/taranis_telemetry does not yet support the X10. ;-P

**Comment by raphaelcoeffic** [comment]
@mikeller yeah, it's called "widgets", and these scripts will need to be modified. And it still lacks the capability of having widgets that can handle keys. But we're working on it, you can bet on that ;-)

**Comment by mikeller** [comment]
@raphaelcoeffic: Just hassling you. :-P You are involved in OpenTx? Also, out of interest, what are the MCU / RAM hardware specs of the X10?

**Comment by raphaelcoeffic** [comment]
@mikeller I did only a couple of small things. Trying to get more involved these days, so I can make my new X10 with opentx the best TX in the world :-D

**Comment by mikeller** [comment]
That's a good goal. Having nice new hardware but firmware that isn't as good as the one on the old stuff is always a big disappointment.

I've seen flashy marketing videos of FrSky's own firmware on the X10. Is it any good, or is it just a non-recent version of OpenTx with some flashy bitmaps slapped on?

**Comment by raphaelcoeffic** [comment]
Totally different. It's quite good for people in need of a UI that basically works like on of the main brands (futaba was named a few times in that context). But it's not my cup of tea when it comes to planes. I would not mind for Quads. probably enough (no LUA though).

**Comment by codecae** [comment]
This issue should now be addressed in release [v1.0.1](https://github.com/betaflight/betaflight-tx-lua-scripts/releases/tag/v1.0.1).

Please download and verify!

**Comment by David-VG** [comment]
Still out of memory here :(

But thanks.

**Comment by codecae** [comment]
I'm wondering now if the other script you're using is eating up resources.    These scripts have been dialed back and optimized in just about every way possible to reduce the memory footprint.  I'm not sure if the other script you're using has undergone the same level of scrutiny.

**Comment by codecae** [comment]
Have you tried temporarily disabling the other script and seeing if it still happens?

**Comment by David-VG** [comment]
It works while using just of both scripts (even if I dont power cycle).

Also works if y manually launch BF/bf.lua while the other script is assigned as the only telemetry script.

But the other script only runs while being displayed (does not background function, just "run").

https://github.com/tozes/taranis_telemetry/blob/master/X9D/TELEMETRY/telem1.lua

As you can see is just a run, divided in 9 functions that just draw the screen. I will try other script just to know if the problem is having 2 telementry scripts or just that "telem1.lua".

**Comment by raphaelcoeffic** [comment]
> But the other script only runs while being displayed (does not background function, just "run").

That does not matter at all: it is still kept in memory, as long as you model is loaded and no one-time script is executed.

**Comment by David-VG** [comment]
Yeah, but it doesent use global variables, just the run loop that just draws.

**Comment by raphaelcoeffic** [comment]
The code is stored in memory as well

**Comment by David-VG** [comment]
Yeah, but only 238 lines. I tought the bitmaps could be the issue but without bitmaps had the same problem.

Tried a hello world without issues and also the snake.lua. Will keep trying.

**Comment by codecae** [comment]
@mikeller how do you feel about the suggestion of dynamic loading of the background script?  ie: setting the background object to nil when the telem screen is loaded and dynamically reload it when the telem screen is exited

**Comment by mikeller** [comment]
@codecae: If that helps with the memory problem (i.e. the entire script is kept on the heap, and not just function pointers), then that's definitely a good idea.

**Comment by brycedjohnson** [comment]
I was getting some memory errors again.  Might have been after updating to the 1.0.1 release rather then the zip you included on here.

I just updated to 2.2.1RC1 opentx and have lau and lauc (not sure if that is needed) for options. (opentx-x9d+-ppmus-multimodule-noheli-lua-luac-en.bin)

**Comment by brycedjohnson** [comment]
Well now it is working and I can't cause the memory error.....

**Comment by codecae** [comment]
I would think that nightly firmware releases are dodgy.  Any reason why you don't want to just stick with the 2.2 stable release?

**Comment by brycedjohnson** [comment]
Testing out some multimodule features that were added.  The last test was with the 2.2.1 RC, so any issues that come up are likely to make it into 2.2.1 if they don't fixed.  I'll likely put 2.2.0 back on there, but I thought I'd update the issue.

**Comment by nikybiasion** [comment]
With opentx 2.2.1 rc3, i let the radio to compile the luac files and then i 've deleted the lua files. This is the only way to avoid memory messages. 
I flash the firmware with lua and luac support

**Comment by codecae** [comment]
@nikybiasion have you tried only copying over the .luac files?  Also -- they have 2.2.1 in general availability.  rc3 may have some bugs that were addressed in the general release.  can you try with the 2.2.1 general release?

**Comment by nikybiasion** [comment]
I've only tried to build luac on my pc and then copy on the radio, but may be the binary format was different and doesn't work, i can try to clean sdcard and copy only luac. I will try the official 2.2.1

**Comment by codecae** [comment]
you shouldn't need to build the luac files yourself.  They're included with the release.

**Comment by codecae** [comment]
if you choose to build them yourself, make sure to use the -s switch to strip the debugging information from the binaries.

**Comment by Ga1j1n** [comment]
I've tested with 2.2.1 release version and the memory issue remains, I had to downgrade which is a shame

**Comment by codecae** [comment]
Which screen causes the memory errors to manifest?

**Comment by Ga1j1n** [comment]
Sorry, I've downgraded now but I'd say you get 3-4 screens in before the error occurs

**Comment by stoms12** [comment]
I am also getting out of memory error. Running Lua script v1.0.1 and OpenTX 2.2.1
I seem to get error either running script manually or as a telemetry screen.
Any progress on fix?

**Comment by codecae** [comment]
Which screen is causing the error?

**Comment by stoms12** [comment]
Can’t even load the script. I am also running https://github.com/tozes/taranis_telemetry

**Comment by nikybiasion** [comment]
I've flashed 2.2.1 opentx release (lua+luac)
I've reinstalled the script, just after entering in the first screen, i can see only 336b free memory...
If i copy only the luac from release 1.0.1 zip file, i get 'bf/x9/rates1.luac incompatible precompiled chunk'
If i copy only lua, all works fine

**Comment by codecae** [comment]
You shouldn't need the lua and luac options unless you plan on using special functions.  Can you try without for testing purposes?

**Comment by nikybiasion** [comment]
Without lua and luac, the radio start with only 144b of free memory, after ciclyng some times in the telemtetry screens, the out of memory message appear

**Comment by stoms12** [comment]
I have re flashed firmware and reinstalled script leaving out the telemetry script.
I am able to open it and change pages, exit out, open again and change pages until I get to rates 2 page. Then I get memory error, this doesn't go away until I restart TX.
Seems like everytime the script opens, it opens a new instance and memory is not cleared.

**Comment by codecae** [comment]
The script is loaded with the model...  It is not reopened every time you
start it.

**Comment by codecae** [comment]
The problem is that the new version of open tx uses more memory that the previous.  This is a very limited and precious resource on these transmitters.

**Comment by stoms12** [comment]
Any ideas on what is causing memory issue then?

**Comment by stoms12** [comment]
So I guess I could try 2.2.0?

**Comment by codecae** [comment]
It is tested and verified on 2.2.0.  this, however, will not guarantee that other telemetry scripts you have running will not get in the way.  They all share the little memory that is available on the hardware.  We have gone to great lengths to ensure ours uses it as efficiently as possible in it's own right.  If another script is running at the same time creating contention, that is out of our control.

**Comment by codecae** [comment]
I'm looking to see if there is any way to squeeze it more.

**Comment by mikeller** [comment]
Looks like it's time to bring back minification.

**Comment by codecae** [comment]
Everything seems to be localized quite well.  Only thing that doesn't appear to be is the values table in the background script.  Its usage size should be fairly benign.  I wonder if something in opentx changed with respect to lua vs luac or garbage collection.

**Comment by mikeller** [comment]
@codecae: I meant the programmatical minification, like what you used before we moved to precompiling the `.luac`. Not sure if it gains us anything when done in addition to the precompilation, but it can't hurt trying.

**Comment by stoms12** [comment]
Seems to be running well now with `opentx-x9d-noheli-lua-luac-en-2.2.1` no memory issues

**Comment by Snake675** [comment]
I get the same issue. Tryed everything fore and back, error message is still occuring after a few page changes [script syntax error BF/ui.lua:335 not nough memory]. Using OpenTX 2.2.1, BF 3.2.3 and tryed BF 3.3.0 #466 testing F.Port with XSR. Its all the same.

**Comment by codecae** [comment]
Has anyone tried copying only the luac files and not the lua files?

**Comment by nikybiasion** [comment]
> If i copy only the luac from release 1.0.1 zip file, i get 'bf/x9/rates1.luac incompatible precompiled chunk'

**Comment by codecae** [comment]
@mikeller I'll try to create a minified version to see if it helps.  Seems
like it may be compiling despite the existence of the lua files.  Feels
like a bandaid, though.

**Comment by codecae** [comment]
Luac files, rather

**Comment by stoms12** [comment]
It seems the solution the worked for me was to flash tx with Luac firmware, only copying the lua files and letting the tx compile luac.

**Comment by codecae** [comment]
You shouldn't need the lua or luac extensions.  It might save even more on
the memory footprint if you leave them out.

**Comment by Snake675** [comment]
Downgraded OpenTX to 2.2.0 and all working fine! Thanks a lot.

**Comment by Reinsettle** [comment]
I'm having the same problem. I just updated to 2.2.1 and got the 335 error. So i put 1.0.1 on it and got both TELEMETRY/bf.lua: 10 and still BF/ui.lua: 335. Should i just go back to 2.2.0?

**Comment by benwap** [comment]
I am using a Crossfire Micro TX on X9D+ and it works better with "open tx 2.2.1". Then I do need to use the VTX page of BF-LUA script. I'm having the same memory problem (under 1.0.1): do you think  that it is  possible to free some memory on the hardware by removing the lua + luac of the unwanted other pages? I mean, is it possible to only use VTX adjusting possibilities?

**Comment by raphaelcoeffic** [comment]
You guys should have a look at this: https://github.com/opentx/opentx/pull/5579

**Comment by Snake675** [comment]
Hi there

Has this been solved?

**Comment by mikeller** [comment]
Not yet.

**Comment by raphaelcoeffic** [comment]
@Snake675 In fact, this is more an opentx issue than anything else.

However, for those who want to try the fix in the opentx PR, here is a zip file with firmwares for X9D & X9D+ (other TXs are not concerned by the issue, as they have more memory available). This is basically vanilla openx 2.2.1 with opentx/opentx#5579 cherry-picked on top of it.

Compile options used: `-DGVARS=YES -DLUA=YES -DHELI=NO -DMULTIMODULE=ON` (+ TX-specific compile option).

[otx-2.2.1-save_mem.zip](https://github.com/betaflight/betaflight-tx-lua-scripts/files/1595194/otx-2.2.1-save_mem.zip)

**Comment by raphaelcoeffic** [comment]
@mikeller @codecae I think we should close this now, as this is really an opentx issue more than anything else.

**Comment by mikeller** [comment]
@raphaelcoeffic: Thanks for building the version above, I tested it and it works. We have added information about this to https://github.com/betaflight/betaflight-tx-lua-scripts and will be updating it there. Closing this.

**Comment by benwap** [comment]
Hi everybody,

Comming back home after a great family moment...
The fix patch for 2.2.1 and X9D+ doesn't work for me.
The Syntax error 335 still arrive when I want to save the VTX changes or
before....

Happy new year to every one.

Ben

Benoit PAILLARD

13bis Avenue des Charrois

04000 DIGNE LES BAINS



04 92 31 94 54

06 20 51 37 48

benwap@orange.fr

www.myspace.com/benoit.paillard <http://www.myspace.com/benoitpaillardtrio>



2017-12-31 21:30 GMT+01:00 Michael Keller <notifications@github.com>:

**Comment by Snake675** [comment]
Hi

For me still the same too.

@benwap: you are living at a very nice place. Stayed there for hollidays a few years ago. I can immagine there are some very nice spots for freestyling around, true?

**Comment by David-VG** [comment]
I've found that the official opentx-x9d+-noheli-lua-luac-internalppm-en-2.2.1.bin works for me. No idea why.

**Comment by raphaelcoeffic** [comment]
@bewap @Snake675 Gents, does it at least work for you on 2.2.0? Are you sure that you were running the binaries I posted here? Fact is, normal 2.2.1 eats up around 4KB more memory compared to 2.2.0, which is then not available for the LUA runtime. The patched version does re-instate these 4KB.

**Comment by benwap** [comment]
Yes it did work fine on 2.2.0, for me.
I just tried (official)
"opentx-x9d+-noheli-lua-luac-internalppm-fr-2.2.1"  and it works as for
David! I have some "Retrying" but it  doesn't fail...
Does internalppm give more memory space?




2018-01-02 17:08 GMT+01:00 Raphael Coeffic <notifications@github.com>:

**Comment by Snake675** [comment]
Same for me. Downgraded to 2.2.0 again and all works fine.

**Comment by benwap** [comment]
I just tried "opentx-x9d+-noheli-lua-luac-sqt5font-fr-2.2.1.bin" official
version and it works!!!  Don't understand at all....
I'm using the obj file  bf-tx-lua 1.01 comming from above.

2018-01-02 17:37 GMT+01:00 Snake675 <notifications@github.com>:

**Comment by raphaelcoeffic** [comment]
just to make it crystal clear to me: the binaries posted in https://github.com/betaflight/betaflight-tx-lua-scripts/issues/97#issuecomment-354604237 DO NOT work for you, whereby some official 2.2.1 builds do work? That makes no sense to me.

**Comment by David-VG** [comment]
I didn't tried the #97. Just tried the noheli-lua-luac-internalppm official build.

noheli-lua-luac-internalppm works for me.
No idea if #97 works but can try if you want to.

**Comment by raphaelcoeffic** [comment]
@David-VG yes, please try these binaries (use only the one for your TX), because these are the binaries that contain the supposed fix to free more memory for LUA on the X9D(+).

**Comment by raphaelcoeffic** [comment]
So just to be sure: I'm talking about this firmware: https://github.com/betaflight/betaflight-tx-lua-scripts/files/1595194/otx-2.2.1-save_mem.zip

**Comment by David-VG** [comment]
with otx-2.2.1-save_mem.zip:

Script syntax error
TELEMETRY/bf.lua:10
not enough memory

**Comment by raphaelcoeffic** [comment]
@David-VG did you actually run only the betaflight script, or do you still have the other one at the same time in memory?

**Comment by David-VG** [comment]
Both in memory. But no error with official noheli-lua-luac-internalppm with both scripts.

**Comment by raphaelcoeffic** [comment]
@David-VG I think we should take your second script out of the equation. Please not that my build did not include the `luac` option, which means that your additional script gets re-compiled everytime, which does not not happen otherwise.

**Comment by David-VG** [comment]
Ok, I tried:

I can use the script a bit more, it does not fail at the first seconds but if I change (for example) to the vtx page and click on save i get:

Script syntax error
BF/ui.lua:335
not enough memory.

I think the script have more memory but needs even more.

Remember the official noheli-lua-luac-internalppm works with both scripts at once. I know it makes no sense.

**Comment by stoms12** [comment]
Guys I'm seeing the same as @David-VG.
Tried the build in https://github.com/betaflight/betaflight-tx-lua-scripts/issues/97#issuecomment-354604237 without the second telemetry script in play.

However both scripts appear to work with `opentx-x9d-noheli-lua-luac-en-2.2.1`
again, no idea why..

**Comment by chargerdude70** [comment]
I'm having this memory issue as well with x9d and BF 3.3.0 kalman filter lua. I get past about sceen 4 or 5, dont recall which, and then error. I dl x9d fw for lua and multimodule use only and get error. I thought I'd try with lua only minus the multimodule option and it went through thew menus with no error but no kalman filter options. Went through it again and got error....

**Comment by brycedjohnson** [comment]
@chargerdude70 The Kalman filter lua isn't part of these lua scripts.  You'll have to check on that wherever you got it

**Comment by Reinsettle** [comment]
I flashed x9d+-savemem-2.2.1 and still got 335 error.

**Comment by blackmennewstyle** [comment]
I just tried opentx-x9d-noheli-lua-luac-en-2.2.1.

It seems to wok indeed but i still got an error after i flashed the firmware when i started up the radio for the first time. I turned off then turned on the radio then i swicthed to a different model and now it's still working whatever i do, i can see the screen after Betaflight / Filters, it was always showing an error at this page apparently: Betaflight / PWM.

**Comment by YogiBear-au** [comment]
Post 97 did not work for me.

**Comment by chargerdude70** [comment]
I wound up flashing back to 2.2.0 to get my LUA to work...

**Comment by YogiBear-au** [comment]
How can you get previous versions ?

**Comment by stoms12** [comment]
@YogiBear-au Try flashing  `opentx-x9d-noheli-lua-luac-en-2.2.1'` to your tx
Thats what worked for me

**Comment by YogiBear-au** [comment]
@storms I have tried that no luck.

I have tried different versions of 2.21 and the "FIX" in post 97.

I have started a with a clean SD card and reinstalled the Lua and card contents. Only thing I haven't done is start with new models. Not sure where they reside? I have not flashed the eprom either.

**Comment by chargerdude70** [comment]
I had 2.2.0 bin from previous flash. I do not know how to get older bin's unless someone has the exact one you are looking for. In my case I had a 9d+ lua multi flash from a previous update

**Comment by robertlacroix** [comment]
I am getting that error after saving VTX settings on 2.2.0 as well as on Raphaels savemem 2.2.1. Not sure what else to try.

In general I think the VTX code is pretty convoluted for what’s it’s doing and I’m not sure if it needs to be.

**Comment by Begna92** [comment]
Look like i solved my problem using the save_mem.zip.
would it be possible to use that firmware with also the sqt5font? i really prefer it to the stock one.
i'm using a x9d not plus version.

**Comment by mikeller** [comment]
@Begna92: I assume a fix for this issue will be included in the next official release of OpenTX, due out in January. Probably not much point building / publishing more patched variants until then...

**Comment by Begna92** [comment]
oh in that case no problem, i'll just wait the official release.
thanks.

**Comment by RipperDrone** [comment]
mem-save .zip working for me as well (OTX 2.2.1 + 1.0.2K (Kalman) BF Lua Script)

**Comment by adamwcsmith** [comment]
Understand that this should be mitigated in an upcoming OpenTX release (2.2.2?), but in the meantime I need access to the VTX screen much more than PID tuning etc.  Is there a way for me to remove the first several screens from the sequence, and keep just the VTX adjustment page?

(Alternately, does removing other models from the unit affect the same memory (even if they are not loaded / activated in a given session) ?  Recognizing that this is an OpenTX question more than BF-tx-lua...)

Just looking for ways to get by until the OpenTX with memory enhancements is released...

**Comment by codecae** [comment]
The screens are ordered in the preload scripts. (ie: x9pre.lua) You can change the order of the screens in this file.  It probably won't help the memory issue, as the script removes from memory the current screen before loading the next.  It doesn't load every screen at startup.

Anything loaded into memory on the taranis affects the overall footprint.  Not sure of the impact of models, specifically, but the less the TX has to keep track of usually results in more available resources.

**Comment by adamwcsmith** [comment]
Thanks for the reply.  I don't have OSD and some VTX settings (e.g. startup-time pit mode) can only be set from SmartAudio, so this gives me a couple of things to try out.

**Comment by deanfourie** [comment]
Where can I find
opentx-x9d+-noheli-lua-luac-sqt5font-fr-2.2.1.bin

Thanks

**Comment by deanfourie** [comment]
or opentx-x9d-noheli-lua-luac-en-2.2.1

**Comment by codecae** [comment]
You can download it using OpenTX Companion.

http://www.open-tx.org/2017/12/16/opentx-2.2.1

**Comment by deanfourie** [comment]
Excuse me for being so stupid! But how do I browse release in companion?

Thanks

**Comment by deanfourie** [comment]
God I feel so god damn dumb right now I cant even downgrade my radio wtf.

**Comment by deanfourie** [comment]
Ok like legit where do we find firmware?

**Comment by mikeller** [comment]
@deanfourie: GitHub is for discussions around **development** of the firmware and applications. For user support please have a look at https://www.rcgroups.com/forums/index.php.

**Comment by Fosch38** [comment]
I also had the "syntax error script.... 335"

Make sure you have copied both "SCRIPT" folder AND "BF" folder on the root folder on your Tx
(exactly as it is from "\bf-tx-lua-1.0.1\obj"   just copy and paste both folders)

Problem solved for me

**Comment by robertlacroix** [comment]
Running the most recent nightly with these configs fixed the problem for me: opentx-x9d+-ppmus-noheli-nogvars-lua-luac-en

**Comment by RipperDrone** [comment]
same here, today's Nightly (OpenTX + Firmware v0015 + SD card content) overcomes memory shortage for Lua. Nice work!

How can I disable the Nightly Build warning 'welcome screen'. Have seen it is part of the compiler options, and I don't know how to compile a special version myself. Seems I have to wait for the RC to make the warning disappear?

**Comment by Punisher79** [comment]
Hello All,

Reflashed with 2.2.1 in tx and installed script 1.0.1. PROBLEM SOLVED! Was running on 2.2.0 on tx with 1.0 script. Also added lua and luac in software specs. Copied the Script folder plus the BF folder that are generated in the obj folder from the zip extract. No more problems on my plus SE.

Hope this helps for you Guys .

**Comment by LIAUTFAM** [comment]
Per above, installed  opentx-x9d+-noheli-lua-sqt5font-**en**-2.2.1.bin   And error went away.

**Comment by r0ndL** [comment]
OK sorry for being such a newb.  I have a new X9D (Mr Steele edition) which has 2.2.1 pre-installed.  From my understanding, I'm not going to be able to run the BetaFlight Lua scripts?  What's the best way for me to have them work?

**Comment by adamwcsmith** [comment]
r0ndL - best answer may be "it depends".  OpenTX can be compiled with many options and inclusions/dis-inclusions that can affect this issue.  Supposedly a future OpenTX (possibly including current non-released builds) will have improvements in general on this front, but this forum is for talking about the BF scripts.

So on that front, I would first suggest that you try it as-is and see what works for you.  If you get the memory error, I don't believe that it affects anything except the running lua script - so it might not work, but if it fails it won't hurt anything else.  If you have problems, look for a video on YouTube from Joshua Bardwell regarding running the BF scripts manually (precompiled luac) instead of dynamically.  It isn't as convenient, but may work as a stop gap until new software mitigates the memory shortage.

**Comment by edww** [comment]
I don't know if it can help but i also have an error when i load script on screen 1 :

> Script syntax error
> TELEMETRY/bf.lua:10
> not enough memory

but if i had "Values" (i think, my taranis is in french and its "Valeurs"..) on screen 1 then "Script > BF" on screen 2 it looks like it works

can it be a bug on page 1 ?

2.2.1
opentx-x9d+-ppmus-noheli-nogvars-lua-sqt5font-fr.bin

**Comment by codecae** [comment]
Please test with this version:
[betaflight-tx-lua-scripts.memtest.zip](https://drive.google.com/open?id=14oqS278DJI6_xZk2wX7axBJ7GqTpqUXq)

**Comment by codecae** [comment]
Something else that may help ...  Contrary to popular belief, it is not necessary to use firmware compiled with lua and luac options in order to use the telemetry scripts.  These options are only required if you intend to use lua in mixer scripts.  The fewer things you enable in the firmware, the less memory it will use.

**Comment by oranmike28** [comment]
@codecae 

I use the V1.0.1. It works but only on the model active when turning on taranis, changing model and then the script doesn't work on all the models. Various errors occur; not enough memory(335 or 10), telemetry protocols not support(40).

**Comment by codecae** [comment]
I'll try to replicate this...  During testing, I was able to change models without any issue.  Maybe this is another issue in 2.2.1.  Just out of curiosity, why is everyone so compelled to use 2.2.1?

**Comment by blackmennewstyle** [comment]
@codecae for me is the fact that external modules can use SBUS now <3
So handy for my Dragon Link V3 UHF gear :D 
And i don't have any issue so far since i upgraded with OpenTX-2.2.1-noheli-lua-luac-en

**Comment by LIAUTFAM** [comment]
No idea if has anything to do with anything... but in order to debug a vtx connection issue, following a joshua bardwell tip I edited x9pre.lua to change the order of the screens displays by the bf script (I kept getting the memory error before I was able to page to the vtx screen), I put the vtx screen first.  For whatever reason... I dont get the low memory script error anymore?
![image](https://user-images.githubusercontent.com/28649695/38185577-2340001c-3692-11e8-8bcf-b9c7439c4eb6.png)

**Comment by Seewatz** [comment]
I have an issue with lua-luac, but only lua solve the problem.

**Comment by oranmike28** [comment]
Hmm so you use opentx 2.2.0?

**Comment by dengorman** [comment]
Same error. Using latest Opentx 2.2.1.  Have tried copying both BF and TELEMETRY folders to sdcard.

**Comment by Seewatz** [comment]
I use latest 2.2.1. With only lua I had no problem.

**Comment by dengorman** [comment]
I just now followed exactly what JB's youtube video instructed, and it seems to be working.

**Comment by mikeller** [comment]
Reopening this to stop users from creating duplicate issues.

**Comment by frizzle101101** [comment]
so i noticed after ive already used and exited from the vtx menu i can no longer open the script untill rebot because the not enough memory error. This does not happen when using and exiting from the pid menu, the next time i open the script it opens to the pid menu no out of memory error.

**Comment by callagga** [comment]
I just downloaded betaflight-tx-lua-scripts v1.0.2 but got the following issue as I was going through (pressing "menu") and when I was on the "Betaflight-RX" page, then pressed "Menu" got this error:

> Script syntax error
> BF/ui.lua:335
> not enough memory

Should I raise a new issue for this?

Note that I have:
- Taranis X9D+
- Opentx version: 2.2.1
- I initially copied/merged the SCRIPTS folder across, then when getting this error went back and copied the root BF folder across also to the tararnis root directory, but same issue

**Comment by hchalouati** [comment]
I want to confirm that I have the same issue with same versions above.

I did a fresh install of the script.

**Comment by turbosi92** [comment]
I wanted to bring this back up simply to ask if the latest opentx fixes the out of memory issue.  I haven't loaded it yet but figured i't ask.  I don't see it mentioned in the release notes but wanted to ask before I take the time to upgrade.

**Comment by floriangaller** [comment]
I tested it with opentx-x9d+-noheli-lua-en-2.2.2 and BF scripts: bf-tx-lua-1.0.2.zip and i have the also the out of memory issue

**Comment by Lazy8onez** [comment]
I also tested it with opentx-x9d+-noheli-lua-en-2.2.2 and BF scripts: bf-tx-lua-1.0.2.zip and havr this issue.
Thing is, if  I go directly to the lua script page after powering the tx ON, it works great. But, if go to that lua page after I, for example, edited settings on my model, it shows this error on page 1.

**Comment by Saschabrix** [comment]
Good morning, 

I have the same issue as the user Florian Galler. 
Opentx-x9d+-noheli-lua-en-2.2.2 and BF scripts: bf-tx-lua-1.0.2.zip.

Same Issue, 
Script Syntax Error
BF/ui.lua:335
not enough memory

**Comment by Lazy8onez** [comment]
I got this working.
I have re-flashed Opentx-x9d+-noheli-lua-luac-en-2.2.2 and BF scripts: bf-tx-lua-1.0.2.zip

the change from my previous try is not modifying any files of the scripts.
As to JB's youtube video, he says there are two options to modify the order of the pages. The second one, modifying x9pre.lua, and moving vtx to the top, seem to be making the issue for me.

**Comment by mikeller** [comment]
@Lazy8onez: Did you recompile the scripts after modifying them? If not, uploading changed source code will force recompilation on the TX, which would explain why this does not work properly.

**Comment by floriangaller** [comment]
I got it also working... my mistake seemed that i used the opentx version without luac...

**Comment by Lazy8onez** [comment]
@mikeller, no I did not

**Comment by mikeller** [comment]
@Lazy8onez: My suspicion is that the on-board compilation is less optimised than off-board, so compiling it before installing will have a better chance of working.

**Comment by Lazy8onez** [comment]
Did you modify any of the files? (like trying to change the order of the pages)
If so, try using the original files.
This was the issue is my case.

**Comment by Snake675** [comment]
@Lazy8onez: Did you call the luac script by menu (as done by jb on his youtube video) or from the telemetry screen?

**Comment by Lazy8onez** [comment]
@Snake675 
Telemetry screen.

**Comment by Pigost** [comment]
I've also got "script syntax error  FB/ui.lua: 335 not enough memory"

**Comment by Snake675** [comment]
I hope this issue will be fixed soon for shure. Some of us seem to have no errors but others do. So what is going on?

**Comment by mikeller** [comment]
@Snake675: Part of the seemingly inconsistent behaviour that gives some users errors for things that work for others could stem from the 'pick and choose' build on the fly system that OpenTX uses to build their firmware - there are over 1000 possible permutations of the every 'release' of OpenTX that users can install, all of which probably have a different RAM consumption...

**Comment by frizzle101101** [comment]
You are correct because usually a build of your own fw on opentx companion
for just Lua script extensin will solve this issue, thats how I solved  it
for me. maybe a note or installation instruction on the Lua scripts release
page would probably help...at this point thou this error can still come up
because of what Michael Keller said about many builds

**Comment by Snake675** [comment]
@frizzle101101 & mikeller
Yes. But I wonder if a own fw without luac helps if you want to open the BF scripts by telemetry screen. If not, I would rather still stick to the previous version of OTX...
